---
metadata.path: /tmp/hibernatus/metadata
backup.interval: 10
backup.folders:
  - /Users/n.fraison/IdeaProjects/hibernatus/hibernatus-agent/src/main/resources
purge.interval: 86400
purge.retention: 1