// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

package fr.bionf.hibernatus.agent.proto;

public final class Db {
  private Db() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileToTreatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileToTreat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>int64 mtime = 2;</code>
     */
    long getMtime();

    /**
     * <code>int64 length = 3;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code FileToTreat}
   */
  public  static final class FileToTreat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileToTreat)
      FileToTreatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileToTreat.newBuilder() to construct.
    private FileToTreat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileToTreat() {
      filename_ = "";
      mtime_ = 0L;
      length_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileToTreat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 16: {

              mtime_ = input.readInt64();
              break;
            }
            case 24: {

              length_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileToTreat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileToTreat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.bionf.hibernatus.agent.proto.Db.FileToTreat.class, fr.bionf.hibernatus.agent.proto.Db.FileToTreat.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <code>string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MTIME_FIELD_NUMBER = 2;
    private long mtime_;
    /**
     * <code>int64 mtime = 2;</code>
     */
    public long getMtime() {
      return mtime_;
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private long length_;
    /**
     * <code>int64 length = 3;</code>
     */
    public long getLength() {
      return length_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (mtime_ != 0L) {
        output.writeInt64(2, mtime_);
      }
      if (length_ != 0L) {
        output.writeInt64(3, length_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (mtime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, mtime_);
      }
      if (length_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.bionf.hibernatus.agent.proto.Db.FileToTreat)) {
        return super.equals(obj);
      }
      fr.bionf.hibernatus.agent.proto.Db.FileToTreat other = (fr.bionf.hibernatus.agent.proto.Db.FileToTreat) obj;

      boolean result = true;
      result = result && getFilename()
          .equals(other.getFilename());
      result = result && (getMtime()
          == other.getMtime());
      result = result && (getLength()
          == other.getLength());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      hash = (37 * hash) + MTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMtime());
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLength());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.bionf.hibernatus.agent.proto.Db.FileToTreat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileToTreat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileToTreat)
        fr.bionf.hibernatus.agent.proto.Db.FileToTreatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileToTreat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileToTreat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.bionf.hibernatus.agent.proto.Db.FileToTreat.class, fr.bionf.hibernatus.agent.proto.Db.FileToTreat.Builder.class);
      }

      // Construct using fr.bionf.hibernatus.agent.proto.Db.FileToTreat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filename_ = "";

        mtime_ = 0L;

        length_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileToTreat_descriptor;
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileToTreat getDefaultInstanceForType() {
        return fr.bionf.hibernatus.agent.proto.Db.FileToTreat.getDefaultInstance();
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileToTreat build() {
        fr.bionf.hibernatus.agent.proto.Db.FileToTreat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileToTreat buildPartial() {
        fr.bionf.hibernatus.agent.proto.Db.FileToTreat result = new fr.bionf.hibernatus.agent.proto.Db.FileToTreat(this);
        result.filename_ = filename_;
        result.mtime_ = mtime_;
        result.length_ = length_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.bionf.hibernatus.agent.proto.Db.FileToTreat) {
          return mergeFrom((fr.bionf.hibernatus.agent.proto.Db.FileToTreat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.bionf.hibernatus.agent.proto.Db.FileToTreat other) {
        if (other == fr.bionf.hibernatus.agent.proto.Db.FileToTreat.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (other.getMtime() != 0L) {
          setMtime(other.getMtime());
        }
        if (other.getLength() != 0L) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.bionf.hibernatus.agent.proto.Db.FileToTreat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.bionf.hibernatus.agent.proto.Db.FileToTreat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private long mtime_ ;
      /**
       * <code>int64 mtime = 2;</code>
       */
      public long getMtime() {
        return mtime_;
      }
      /**
       * <code>int64 mtime = 2;</code>
       */
      public Builder setMtime(long value) {
        
        mtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mtime = 2;</code>
       */
      public Builder clearMtime() {
        
        mtime_ = 0L;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>int64 length = 3;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>int64 length = 3;</code>
       */
      public Builder setLength(long value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileToTreat)
    }

    // @@protoc_insertion_point(class_scope:FileToTreat)
    private static final fr.bionf.hibernatus.agent.proto.Db.FileToTreat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.bionf.hibernatus.agent.proto.Db.FileToTreat();
    }

    public static fr.bionf.hibernatus.agent.proto.Db.FileToTreat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileToTreat>
        PARSER = new com.google.protobuf.AbstractParser<FileToTreat>() {
      public FileToTreat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileToTreat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileToTreat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileToTreat> getParserForType() {
      return PARSER;
    }

    public fr.bionf.hibernatus.agent.proto.Db.FileToTreat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileBackupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileBackup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */
    int getReferencesCount();
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */
    boolean containsReferences(
        long key);
    /**
     * Use {@link #getReferencesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
    getReferences();
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */
    java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
    getReferencesMap();
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrDefault(
        long key,
        fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile defaultValue);
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code FileBackup}
   */
  public  static final class FileBackup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileBackup)
      FileBackupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileBackup.newBuilder() to construct.
    private FileBackup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileBackup() {
      filename_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileBackup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                references_ = com.google.protobuf.MapField.newMapField(
                    ReferencesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
              references__ = input.readMessage(
                  ReferencesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              references_.getMutableMap().put(
                  references__.getKey(), references__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetReferences();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.bionf.hibernatus.agent.proto.Db.FileBackup.class, fr.bionf.hibernatus.agent.proto.Db.FileBackup.Builder.class);
    }

    public interface AwsFileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:FileBackup.AwsFile)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string awsObject = 1;</code>
       */
      java.lang.String getAwsObject();
      /**
       * <code>string awsObject = 1;</code>
       */
      com.google.protobuf.ByteString
          getAwsObjectBytes();

      /**
       * <code>int64 length = 2;</code>
       */
      long getLength();

      /**
       * <code>int64 lastModified = 3;</code>
       */
      long getLastModified();

      /**
       * <code>int64 lastBackuped = 4;</code>
       */
      long getLastBackuped();

      /**
       * <code>int64 deleteEpoch = 5;</code>
       */
      long getDeleteEpoch();
    }
    /**
     * Protobuf type {@code FileBackup.AwsFile}
     */
    public  static final class AwsFile extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:FileBackup.AwsFile)
        AwsFileOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use AwsFile.newBuilder() to construct.
      private AwsFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private AwsFile() {
        awsObject_ = "";
        length_ = 0L;
        lastModified_ = 0L;
        lastBackuped_ = 0L;
        deleteEpoch_ = 0L;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private AwsFile(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                awsObject_ = s;
                break;
              }
              case 16: {

                length_ = input.readInt64();
                break;
              }
              case 24: {

                lastModified_ = input.readInt64();
                break;
              }
              case 32: {

                lastBackuped_ = input.readInt64();
                break;
              }
              case 40: {

                deleteEpoch_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_AwsFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_AwsFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.class, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.Builder.class);
      }

      public static final int AWSOBJECT_FIELD_NUMBER = 1;
      private volatile java.lang.Object awsObject_;
      /**
       * <code>string awsObject = 1;</code>
       */
      public java.lang.String getAwsObject() {
        java.lang.Object ref = awsObject_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          awsObject_ = s;
          return s;
        }
      }
      /**
       * <code>string awsObject = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAwsObjectBytes() {
        java.lang.Object ref = awsObject_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          awsObject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LENGTH_FIELD_NUMBER = 2;
      private long length_;
      /**
       * <code>int64 length = 2;</code>
       */
      public long getLength() {
        return length_;
      }

      public static final int LASTMODIFIED_FIELD_NUMBER = 3;
      private long lastModified_;
      /**
       * <code>int64 lastModified = 3;</code>
       */
      public long getLastModified() {
        return lastModified_;
      }

      public static final int LASTBACKUPED_FIELD_NUMBER = 4;
      private long lastBackuped_;
      /**
       * <code>int64 lastBackuped = 4;</code>
       */
      public long getLastBackuped() {
        return lastBackuped_;
      }

      public static final int DELETEEPOCH_FIELD_NUMBER = 5;
      private long deleteEpoch_;
      /**
       * <code>int64 deleteEpoch = 5;</code>
       */
      public long getDeleteEpoch() {
        return deleteEpoch_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getAwsObjectBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, awsObject_);
        }
        if (length_ != 0L) {
          output.writeInt64(2, length_);
        }
        if (lastModified_ != 0L) {
          output.writeInt64(3, lastModified_);
        }
        if (lastBackuped_ != 0L) {
          output.writeInt64(4, lastBackuped_);
        }
        if (deleteEpoch_ != 0L) {
          output.writeInt64(5, deleteEpoch_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getAwsObjectBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, awsObject_);
        }
        if (length_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, length_);
        }
        if (lastModified_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, lastModified_);
        }
        if (lastBackuped_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, lastBackuped_);
        }
        if (deleteEpoch_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, deleteEpoch_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile)) {
          return super.equals(obj);
        }
        fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile other = (fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile) obj;

        boolean result = true;
        result = result && getAwsObject()
            .equals(other.getAwsObject());
        result = result && (getLength()
            == other.getLength());
        result = result && (getLastModified()
            == other.getLastModified());
        result = result && (getLastBackuped()
            == other.getLastBackuped());
        result = result && (getDeleteEpoch()
            == other.getDeleteEpoch());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + AWSOBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getAwsObject().hashCode();
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLength());
        hash = (37 * hash) + LASTMODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastModified());
        hash = (37 * hash) + LASTBACKUPED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastBackuped());
        hash = (37 * hash) + DELETEEPOCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDeleteEpoch());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code FileBackup.AwsFile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:FileBackup.AwsFile)
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_AwsFile_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_AwsFile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.class, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.Builder.class);
        }

        // Construct using fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          awsObject_ = "";

          length_ = 0L;

          lastModified_ = 0L;

          lastBackuped_ = 0L;

          deleteEpoch_ = 0L;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_AwsFile_descriptor;
        }

        public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getDefaultInstanceForType() {
          return fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.getDefaultInstance();
        }

        public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile build() {
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile buildPartial() {
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile result = new fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile(this);
          result.awsObject_ = awsObject_;
          result.length_ = length_;
          result.lastModified_ = lastModified_;
          result.lastBackuped_ = lastBackuped_;
          result.deleteEpoch_ = deleteEpoch_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile) {
            return mergeFrom((fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile other) {
          if (other == fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.getDefaultInstance()) return this;
          if (!other.getAwsObject().isEmpty()) {
            awsObject_ = other.awsObject_;
            onChanged();
          }
          if (other.getLength() != 0L) {
            setLength(other.getLength());
          }
          if (other.getLastModified() != 0L) {
            setLastModified(other.getLastModified());
          }
          if (other.getLastBackuped() != 0L) {
            setLastBackuped(other.getLastBackuped());
          }
          if (other.getDeleteEpoch() != 0L) {
            setDeleteEpoch(other.getDeleteEpoch());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object awsObject_ = "";
        /**
         * <code>string awsObject = 1;</code>
         */
        public java.lang.String getAwsObject() {
          java.lang.Object ref = awsObject_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            awsObject_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string awsObject = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAwsObjectBytes() {
          java.lang.Object ref = awsObject_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            awsObject_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string awsObject = 1;</code>
         */
        public Builder setAwsObject(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          awsObject_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string awsObject = 1;</code>
         */
        public Builder clearAwsObject() {
          
          awsObject_ = getDefaultInstance().getAwsObject();
          onChanged();
          return this;
        }
        /**
         * <code>string awsObject = 1;</code>
         */
        public Builder setAwsObjectBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          awsObject_ = value;
          onChanged();
          return this;
        }

        private long length_ ;
        /**
         * <code>int64 length = 2;</code>
         */
        public long getLength() {
          return length_;
        }
        /**
         * <code>int64 length = 2;</code>
         */
        public Builder setLength(long value) {
          
          length_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 length = 2;</code>
         */
        public Builder clearLength() {
          
          length_ = 0L;
          onChanged();
          return this;
        }

        private long lastModified_ ;
        /**
         * <code>int64 lastModified = 3;</code>
         */
        public long getLastModified() {
          return lastModified_;
        }
        /**
         * <code>int64 lastModified = 3;</code>
         */
        public Builder setLastModified(long value) {
          
          lastModified_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 lastModified = 3;</code>
         */
        public Builder clearLastModified() {
          
          lastModified_ = 0L;
          onChanged();
          return this;
        }

        private long lastBackuped_ ;
        /**
         * <code>int64 lastBackuped = 4;</code>
         */
        public long getLastBackuped() {
          return lastBackuped_;
        }
        /**
         * <code>int64 lastBackuped = 4;</code>
         */
        public Builder setLastBackuped(long value) {
          
          lastBackuped_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 lastBackuped = 4;</code>
         */
        public Builder clearLastBackuped() {
          
          lastBackuped_ = 0L;
          onChanged();
          return this;
        }

        private long deleteEpoch_ ;
        /**
         * <code>int64 deleteEpoch = 5;</code>
         */
        public long getDeleteEpoch() {
          return deleteEpoch_;
        }
        /**
         * <code>int64 deleteEpoch = 5;</code>
         */
        public Builder setDeleteEpoch(long value) {
          
          deleteEpoch_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 deleteEpoch = 5;</code>
         */
        public Builder clearDeleteEpoch() {
          
          deleteEpoch_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:FileBackup.AwsFile)
      }

      // @@protoc_insertion_point(class_scope:FileBackup.AwsFile)
      private static final fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile();
      }

      public static fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<AwsFile>
          PARSER = new com.google.protobuf.AbstractParser<AwsFile>() {
        public AwsFile parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AwsFile(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<AwsFile> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<AwsFile> getParserForType() {
        return PARSER;
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <code>string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCES_FIELD_NUMBER = 2;
    private static final class ReferencesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>newDefaultInstance(
                  fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_ReferencesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> references_;
    private com.google.protobuf.MapField<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
    internalGetReferences() {
      if (references_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ReferencesDefaultEntryHolder.defaultEntry);
      }
      return references_;
    }

    public int getReferencesCount() {
      return internalGetReferences().getMap().size();
    }
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    public boolean containsReferences(
        long key) {
      
      return internalGetReferences().getMap().containsKey(key);
    }
    /**
     * Use {@link #getReferencesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> getReferences() {
      return getReferencesMap();
    }
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    public java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> getReferencesMap() {
      return internalGetReferences().getMap();
    }
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrDefault(
        long key,
        fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile defaultValue) {
      
      java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> map =
          internalGetReferences().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
     */

    public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> map =
          internalGetReferences().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetReferences(),
          ReferencesDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      for (java.util.Map.Entry<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> entry
           : internalGetReferences().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
        references__ = ReferencesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, references__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.bionf.hibernatus.agent.proto.Db.FileBackup)) {
        return super.equals(obj);
      }
      fr.bionf.hibernatus.agent.proto.Db.FileBackup other = (fr.bionf.hibernatus.agent.proto.Db.FileBackup) obj;

      boolean result = true;
      result = result && getFilename()
          .equals(other.getFilename());
      result = result && internalGetReferences().equals(
          other.internalGetReferences());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      if (!internalGetReferences().getMap().isEmpty()) {
        hash = (37 * hash) + REFERENCES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetReferences().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.bionf.hibernatus.agent.proto.Db.FileBackup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileBackup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileBackup)
        fr.bionf.hibernatus.agent.proto.Db.FileBackupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetReferences();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableReferences();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.bionf.hibernatus.agent.proto.Db.FileBackup.class, fr.bionf.hibernatus.agent.proto.Db.FileBackup.Builder.class);
      }

      // Construct using fr.bionf.hibernatus.agent.proto.Db.FileBackup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filename_ = "";

        internalGetMutableReferences().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.bionf.hibernatus.agent.proto.Db.internal_static_FileBackup_descriptor;
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup getDefaultInstanceForType() {
        return fr.bionf.hibernatus.agent.proto.Db.FileBackup.getDefaultInstance();
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup build() {
        fr.bionf.hibernatus.agent.proto.Db.FileBackup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup buildPartial() {
        fr.bionf.hibernatus.agent.proto.Db.FileBackup result = new fr.bionf.hibernatus.agent.proto.Db.FileBackup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.filename_ = filename_;
        result.references_ = internalGetReferences();
        result.references_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.bionf.hibernatus.agent.proto.Db.FileBackup) {
          return mergeFrom((fr.bionf.hibernatus.agent.proto.Db.FileBackup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.bionf.hibernatus.agent.proto.Db.FileBackup other) {
        if (other == fr.bionf.hibernatus.agent.proto.Db.FileBackup.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        internalGetMutableReferences().mergeFrom(
            other.internalGetReferences());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.bionf.hibernatus.agent.proto.Db.FileBackup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.bionf.hibernatus.agent.proto.Db.FileBackup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> references_;
      private com.google.protobuf.MapField<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
      internalGetReferences() {
        if (references_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ReferencesDefaultEntryHolder.defaultEntry);
        }
        return references_;
      }
      private com.google.protobuf.MapField<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
      internalGetMutableReferences() {
        onChanged();;
        if (references_ == null) {
          references_ = com.google.protobuf.MapField.newMapField(
              ReferencesDefaultEntryHolder.defaultEntry);
        }
        if (!references_.isMutable()) {
          references_ = references_.copy();
        }
        return references_;
      }

      public int getReferencesCount() {
        return internalGetReferences().getMap().size();
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public boolean containsReferences(
          long key) {
        
        return internalGetReferences().getMap().containsKey(key);
      }
      /**
       * Use {@link #getReferencesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> getReferences() {
        return getReferencesMap();
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> getReferencesMap() {
        return internalGetReferences().getMap();
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrDefault(
          long key,
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile defaultValue) {
        
        java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> map =
            internalGetReferences().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile getReferencesOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> map =
            internalGetReferences().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearReferences() {
        internalGetMutableReferences().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public Builder removeReferences(
          long key) {
        
        internalGetMutableReferences().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile>
      getMutableReferences() {
        return internalGetMutableReferences().getMutableMap();
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */
      public Builder putReferences(
          long key,
          fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableReferences().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int64, .FileBackup.AwsFile&gt; references = 2;</code>
       */

      public Builder putAllReferences(
          java.util.Map<java.lang.Long, fr.bionf.hibernatus.agent.proto.Db.FileBackup.AwsFile> values) {
        internalGetMutableReferences().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileBackup)
    }

    // @@protoc_insertion_point(class_scope:FileBackup)
    private static final fr.bionf.hibernatus.agent.proto.Db.FileBackup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.bionf.hibernatus.agent.proto.Db.FileBackup();
    }

    public static fr.bionf.hibernatus.agent.proto.Db.FileBackup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileBackup>
        PARSER = new com.google.protobuf.AbstractParser<FileBackup>() {
      public FileBackup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileBackup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileBackup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileBackup> getParserForType() {
      return PARSER;
    }

    public fr.bionf.hibernatus.agent.proto.Db.FileBackup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileToTreat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileToTreat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileBackup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileBackup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileBackup_AwsFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileBackup_AwsFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileBackup_ReferencesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileBackup_ReferencesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010db.proto\">\n\013FileToTreat\022\020\n\010filename\030\001 " +
      "\001(\t\022\r\n\005mtime\030\002 \001(\003\022\016\n\006length\030\003 \001(\003\"\206\002\n\nF" +
      "ileBackup\022\020\n\010filename\030\001 \001(\t\022/\n\nreference" +
      "s\030\002 \003(\0132\033.FileBackup.ReferencesEntry\032m\n\007" +
      "AwsFile\022\021\n\tawsObject\030\001 \001(\t\022\016\n\006length\030\002 \001" +
      "(\003\022\024\n\014lastModified\030\003 \001(\003\022\024\n\014lastBackuped" +
      "\030\004 \001(\003\022\023\n\013deleteEpoch\030\005 \001(\003\032F\n\017Reference" +
      "sEntry\022\013\n\003key\030\001 \001(\003\022\"\n\005value\030\002 \001(\0132\023.Fil" +
      "eBackup.AwsFile:\0028\001B!\n\037fr.bionf.hibernat" +
      "us.agent.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FileToTreat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileToTreat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileToTreat_descriptor,
        new java.lang.String[] { "Filename", "Mtime", "Length", });
    internal_static_FileBackup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileBackup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileBackup_descriptor,
        new java.lang.String[] { "Filename", "References", });
    internal_static_FileBackup_AwsFile_descriptor =
      internal_static_FileBackup_descriptor.getNestedTypes().get(0);
    internal_static_FileBackup_AwsFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileBackup_AwsFile_descriptor,
        new java.lang.String[] { "AwsObject", "Length", "LastModified", "LastBackuped", "DeleteEpoch", });
    internal_static_FileBackup_ReferencesEntry_descriptor =
      internal_static_FileBackup_descriptor.getNestedTypes().get(1);
    internal_static_FileBackup_ReferencesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileBackup_ReferencesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
